### ISSUE TITLE
NER example JSON does not work

### ISSUE THREAD

**Issue by DSLituiev** [OpenHumanAnnotation/open-human-annotation-task-format#7]
I am figuring out how to  import my own annotations. Using [this example](https://github.com/UniversalDataTool/udt-format/blob/master/interfaces/text_entity_recognition.md) linked from the import window ("See the UDT JSON format"), I am getting an error:

<img width="613" alt="Screen Shot 2020-10-07 at 15 06 45" src="https://user-images.githubusercontent.com/8426290/95393189-fe607c80-08ae-11eb-8a6f-abf3975e0740.png">

I see that the issue is probably because of `//` comments. After fixing that I am running into an issue with question marks, and then with the fact that `text`, `label` and other tags are not quoted. 

It would be great to have a minimal working example that one can plug-and-play.

After massaging it to make it swallow it, I am not able to find where that example went. When I go to the "Label" page, there still 0 documents there. How can I find the imported sample now?

**Comment by DSLituiev** [comment]
Also it is not clear what is the difference between "samples" and "examples". Providing annotations with either of them seems to have no effect -- only plain text remains if imported with "samples". But "examples" seem to  be not imported at all.

Is it expected behaviour? Would it be a good idea to document it?

**Comment by seveibar** [comment]
Hey @DSLituiev, sorry for the slow response. The JSON samples were a bit hastily written, they're not valid "JSON" but they are valid javascript.

**Comment by seveibar** [comment]
The "examples" array is also no longer used. These will be updated.

**Comment by seveibar** [comment]
I've made the updates to make this easier to read and copy and paste into the UDT tool.
